version: '3.1'
services:
  stats-server:
    build: ewm-statistics/ewm-statistics-business
    image: ewm-statistics
    container_name: ewm-statistics
    ports:
      - "9090:9090"
    depends_on:
      - stats-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://stats-db:6541/stat
      - DB_NAME=stat
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - DB_HOST=stats-db
      - DB_PORT=6541
      #- TZ=Europe/Moscow

  stats-db:
    image: postgres:14-alpine
    container_name: ewm-stats-db
    command: postgres -c port=6541
    volumes:
      - var/lib/postgresql/data
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_DB=stat
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      #- TZ=Europe/Moscow
      #- PGTZ=Europe/Moscow

  ewm-service:
    build: ewm-core/ewm-core-business
    image: ewm-core
    container_name: ewm-core
    ports:
      - "8080:8080"
    depends_on:
      - ewm-db
      - stats-server
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ewm-db:6542/ewm
      - DB_NAME=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      - DB_HOST=ewm-db
      - DB_PORT=6542
      - EWM_STATS_SERVER_URL=http://stats-server:9090
      #- TZ=Europe/Moscow

  ewm-db:
    image: postgres:14-alpine
    container_name: ewm-core-db
    command: postgres -c port=6542
    volumes:
      - var/lib/postgresql/data
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=ewm
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=ewm
      #- TZ=Europe/Moscow
      #- PGTZ=Europe/Moscow
