DROP TABLE IF EXISTS endpoint_hits CASCADE;

CREATE TABLE IF NOT EXISTS endpoint_hits
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    app        VARCHAR                     NOT NULL,
    uri        VARCHAR                     NOT NULL,
    ip         VARCHAR                     NOT NULL,
    created_on TIMESTAMP WITHOUT TIME ZONE NOT NULL
);